document.addEventListener('DOMContentLoaded',()=>{
const KARATS=[8,14,18,20,22,24];
const defaults={max:86,pawn1:55,pawn2:75,offers:[12,29,49,75],greenEnd:30,yellowEnd:50,orangeEnd:70};
function readConfig(){try{const saved=JSON.parse(localStorage.getItem('goldConfig')||'null');return saved&&typeof saved==='object'?{...defaults,...saved,offers:Array.isArray(saved.offers)&&saved.offers.length===4?saved.offers:defaults.offers}:defaults}catch{return defaults}}
let config=readConfig();
const state={weights:Object.fromEntries(KARATS.map(k=>[k,0])),price:75};
const eur=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number.isFinite(v)?v:0);
const n=v=>Number.parseFloat(String(v??'').replace(/\s/g,'').replace(',','.'))||0;
const $=id=>document.getElementById(id);
function enableCommaDecimals(){document.querySelectorAll('input[type="number"]').forEach(input=>{input.type='text'});document.querySelectorAll('input[data-decimal], input[data-karat], #pawnGrams, #pawnMinRate, #pawnMaxRate, #cfgMax, #cfgPawn1, #cfgPawn2, #cfgOffer1, #cfgOffer2, #cfgOffer3, #cfgOffer4, #cfgGreenEnd, #cfgYellowEnd, #cfgOrangeEnd').forEach(input=>{input.inputMode='decimal';input.setAttribute('pattern','[0-9]*[,.]?[0-9]*');input.setAttribute('autocomplete','off');input.removeAttribute('min');input.removeAttribute('max');input.removeAttribute('step')})}
function renderInputs(){$('karatInputs').innerHTML=KARATS.map(k=>`<div class="karat-card"><label>${k}K</label><input data-karat="${k}" data-decimal type="text" inputmode="decimal" pattern="[0-9]*[,.]?[0-9]*" placeholder="0,00" autocomplete="off" enterkeyhint="done"><em>gramos</em></div>`).join('');document.querySelectorAll('[data-karat]').forEach(i=>i.addEventListener('input',e=>{state.weights[e.target.dataset.karat]=n(e.target.value);calculate()}))}
function applyRangeColor(){const slider=$('priceRange');if(!slider)return;const max=Math.max(1,n(config.max)||defaults.max);let green=Math.min(Math.max(1,n(config.greenEnd)||defaults.greenEnd),max);let yellow=Math.min(Math.max(green,n(config.yellowEnd)||defaults.yellowEnd),max);let orange=Math.min(Math.max(yellow,n(config.orangeEnd)||defaults.orangeEnd),max);const pct=v=>((v-1)/(max-1))*100;slider.style.background=`linear-gradient(to right,rgba(93,174,125,.42) 0%,rgba(93,174,125,.42) ${pct(green)}%,rgba(211,193,86,.42) ${pct(green)}%,rgba(211,193,86,.42) ${pct(yellow)}%,rgba(218,137,76,.42) ${pct(yellow)}%,rgba(218,137,76,.42) ${pct(orange)}%,rgba(196,91,91,.42) ${pct(orange)}%,rgba(196,91,91,.42) 100%)`;slider.style.setProperty('--range-green',String(green));slider.style.setProperty('--range-yellow',String(yellow));slider.style.setProperty('--range-orange',String(orange))}
function applyPriceLimit(){const slider=$('priceRange');if(!slider)return;const max=Math.max(1,n(config.max)||defaults.max);slider.max=String(max);if(state.price>max)state.price=max;if(state.price<1)state.price=1;slider.value=String(Math.min(state.price,max));$('referencePrice').textContent=`${state.price.toFixed(2)} €/g`;if($('maxRangeLabel'))$('maxRangeLabel').textContent=`${max.toFixed(2)} €/g`;applyRangeColor()}
function calculate(){const total=Object.values(state.weights).reduce((a,b)=>a+b,0);const eq=KARATS.reduce((a,k)=>a+state.weights[k]*(k/18),0);const fine=KARATS.reduce((a,k)=>a+state.weights[k]*(k/24),0);const purity=total?fine/total*100:0;$('totalWeight').textContent=`${total.toFixed(2)} g · equivalente 18K: ${eq.toFixed(2)} g`;$('totalValue').textContent=eur(eq*state.price);$('grossValue').textContent=eur(eq*state.price);$('eq18').textContent=`${eq.toFixed(2)} g`;$('purity').textContent=`${purity.toFixed(1)}%`;$('buyWeight').textContent=`${eq.toFixed(2)} g`;renderOffers(eq);renderPawn()}
function renderOffers(eq){const offers=[...config.offers,config.max].sort((a,b)=>a-b);$('offerTable').innerHTML=offers.map((r,i)=>`<div class="offer"><div><span>${r===config.max?'Máximo':'Oferta '+(i+1)}</span><div class="rate">${Number(r).toFixed(2)} €/g</div></div><div class="amount">${eur(eq*r)}</div></div>`).join('');$('maxOffer').textContent=`${Number(config.max).toFixed(2)} €/g`}
function renderPawn(){const grams=n($('pawnGrams')?.value),min=n($('pawnMinRate')?.value),max=n($('pawnMaxRate')?.value);if($('pawnMinTotal'))$('pawnMinTotal').textContent=eur(grams*min);if($('pawnMaxTotal'))$('pawnMaxTotal').textContent=eur(grams*max)}
function loadConfig(){config=readConfig();$('cfgMax').value=config.max;$('cfgPawn1').value=config.pawn1;$('cfgPawn2').value=config.pawn2;config.offers.forEach((v,i)=>{if($(`cfgOffer${i+1}`))$(`cfgOffer${i+1}`).value=v});if($('cfgGreenEnd'))$('cfgGreenEnd').value=config.greenEnd;if($('cfgYellowEnd'))$('cfgYellowEnd').value=config.yellowEnd;if($('cfgOrangeEnd'))$('cfgOrangeEnd').value=config.orangeEnd;$('pawnMinRate').value=config.pawn1;$('pawnMaxRate').value=config.pawn2;applyPriceLimit()}
function renderHistory(){const list=$('historyList');if(!list)return;let items=[];try{items=JSON.parse(localStorage.getItem('goldHistory')||'[]')}catch{}list.innerHTML=items.map(x=>`<div class="history-item"><strong>${eur(x.value)}</strong><div>${Number(x.weight).toFixed(2)} g · ${Number(x.eq).toFixed(2)} g eq. 18K</div><small>${x.date}</small></div>`).join('')}
function clearAll(){document.querySelectorAll('[data-karat]').forEach(i=>i.value='');KARATS.forEach(k=>state.weights[k]=0);calculate()}
function setTheme(mode){const isLight=mode==='light';document.body.classList.toggle('light',isLight);document.documentElement.classList.toggle('light',isLight);document.documentElement.dataset.theme=isLight?'light':'dark';localStorage.setItem('goldTheme',isLight?'light':'dark');const btn=$('themeBtn');if(btn){btn.textContent=isLight?'🌙':'☀️';btn.setAttribute('aria-label',isLight?'Activar modo noche':'Activar modo día');btn.setAttribute('title',isLight?'Activar modo noche':'Activar modo día');btn.setAttribute('aria-pressed',String(isLight))}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',isLight?'#f5f2ea':'#111111')}
function toggleTheme(){setTheme(document.documentElement.dataset.theme==='light'?'dark':'light')}
function toggleView(viewId){const target=$(viewId);if(!target)return;document.querySelectorAll('.nav-item').forEach(x=>{const active=x.dataset.view===viewId;x.classList.toggle('active',active);x.setAttribute('aria-current',active?'page':'false')});document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===viewId));if(viewId==='historial')renderHistory();if(viewId==='empenos')renderPawn();window.scrollTo({top:0,left:0,behavior:'instant'})}
$('priceRange').addEventListener('input',e=>{state.price=Math.min(n(e.target.value),n(config.max)||defaults.max);$('referencePrice').textContent=`${state.price.toFixed(2)} €/g`;applyRangeColor();calculate()});
$('clearBtn').addEventListener('click',clearAll);
$('saveConfig').addEventListener('click',()=>{const max=n($('cfgMax').value)||defaults.max;let green=n($('cfgGreenEnd').value)||defaults.greenEnd;let yellow=n($('cfgYellowEnd').value)||defaults.yellowEnd;let orange=n($('cfgOrangeEnd').value)||defaults.orangeEnd;green=Math.min(Math.max(1,green),max);yellow=Math.min(Math.max(green,yellow),max);orange=Math.min(Math.max(yellow,orange),max);config={max,pawn1:n($('cfgPawn1').value)||defaults.pawn1,pawn2:n($('cfgPawn2').value)||defaults.pawn2,offers:[1,2,3,4].map(i=>n($(`cfgOffer${i}`).value)||defaults.offers[i-1]),greenEnd:green,yellowEnd:yellow,orangeEnd:orange};localStorage.setItem('goldConfig',JSON.stringify(config));loadConfig();calculate();alert('Configuración guardada')});
const bottomNav=document.querySelector('.bottom-nav');
if(bottomNav)bottomNav.addEventListener('click',e=>{const btn=e.target.closest('.nav-item');if(btn&&bottomNav.contains(btn)){e.preventDefault();e.stopPropagation();toggleView(btn.dataset.view)}},false);
['pawnGrams','pawnMinRate','pawnMaxRate'].forEach(id=>$(id).addEventListener('input',renderPawn));
const themeBtn=$('themeBtn');
if(themeBtn)themeBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();toggleTheme()},false);
document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});
document.addEventListener('gestureend',e=>e.preventDefault(),{passive:false});
let lastTouchEnd=0;
document.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouchEnd<=300)e.preventDefault();lastTouchEnd=now},{passive:false});
setTheme(localStorage.getItem('goldTheme')==='light'?'light':'dark');
renderInputs();loadConfig();enableCommaDecimals();renderHistory();calculate();renderPawn();
});